import { AllFilesDropDownData, ForensicsSelectedData, MemorySelectedData } from "../interfaceBoard";

export const initMemoryDropDownSelected: MemorySelectedData = { 
    isMemoryGroupSelected: true,
    processName: "",
    processConnectIP: "",
    dynamicCommand: "",
    processMD5: "",
    processPath: "",
    parentProcessPath: "",
    digitalSign: "",
    importOtherDLL: "",
    processId: "",
    riskLevel: ['三', "四"],
    injectActive: ['非PE程式碼', '無'],
    processBeInjected: ['無'],
    boot: ['AutoRun', '無'],
    hook: ['無'],
    hide: ['File', '無'] 
}

export const initForensicsSelectedData: ForensicsSelectedData = { 
    isForensicsSelected: true,
    keywordType: 'keywordType',
    keyword: 'keyword',
    browsingHistoryAndBookmarks: false,
    chromeBrowsingHistory: false,
    chromeDownloadHistory: false,
    chromeKeywordSearchHistory: false,
    chromeLoginAccountAndPassword: false,
    chromeBookmarks: false,
    cacheAndCookieHistory: false,
    chromeCache: false,
    chromeCookies: false,
    edgeCache: false,
    edgeCookies: false,
    ieCache: false,
    firefoxCache: false,
    firefoxCookies: false,
    currentNetworkConnectionsHistory: false,
    internetInformation: false,
    unlimitedBasicInformation: false,
    internetResources: false,
    recentlyExecutedSoftwareLog: false,
    softwareInstalled: false,
    detailedSystemServices: false,
    remoteDesktopLoginAccountPassword: false,
    systemInformation: false,
    prefetch: false,
    scheduleWork: false,
    programNetworkTrafficTrace: false,
    dnsInformation: false,
    generalSystemServices: false,
    bootProgram: false,
    jumpList: false,
    muicache: false,
    applicationLogFiles: false,
    machineCodeTraces: false,
    programReadAndWriteTraces: false,
    evanescentRecords: false,
    executeProgram: false,
    fileOpenedByTheProgram: false,
    programConnectionInformation: false,
    arpCache: false,
    recentlyOpenedFileHistory: false,
    relativeShortcuts: false,
    maasterUserProfiles: false,
    windowsActivity: false,
    openFolderPath: false,
    recentlyOpenedFile: false, usbUsageDeviceRecord: false, usbDeviceInformation: false, syslogFile: false, securityLogFile: false, emailListReacord: false, emailPath: false, emailListRecord: false, }

export const initAllFilesDropDownData: AllFilesDropDownData = { isAllFilesSelected: true, keyPath: '', keywordType: '影音檔', keywordFileName: '', keywordContent: '', fileSize: 'min', fileSizeValue: 0, fileUnit: 'MB', onlySearchDeletedFile: false }
